### ISSUE TITLE
Dependency on underscore missing?

### ISSUE THREAD

**Issue by JockeCK** [motss/jv-datepicker#2]
It seems you are depending on the library underscore for functions such as "_.isNumber".

However, there is no trace of this dependency in your code/json? 

Personally I would love an solution that does not depend on underscore.
Like: 
function isNumeric(n) {
  return !isNaN(parseFloat(n)) && isFinite(n);
} 
(example, just an quick google)
Since you at an glance don't seem to depend all that heavily upon the library. But obviously up to you.

**Comment by motss** [comment]
@JockeCK This might due to the fact that I'm a [Lodash](https://github.com/lodash/lodash) user. I always use the library with Polymer even though you can achieve something in Javascript without the need of Lodash just like what you mentioned earlier. Thus, instead of including the `<script src="../lodash/dist/lodash.min.js"></script>` inside the element, I think I should load the script at top level document which means that you can find the `script` tag inside the `demo/index.html`. Well, Lodash is a great library and if you have `web-component-tester` installed, you will probably get the Lodash installed as well.

**Comment by JockeCK** [comment]
Thank you for the quick explanation! 

Got your component up and running after adding pathway to bower installation of lodash.

**Comment by motss** [comment]
Cool!

**Comment by motss** [comment]
No longer depend on Lodash. See commit 89777d38f287ef9571281c6a57d9bc04027543d9.
